### ISSUE TITLE
error: unbalanced parenthesis at position 43

### ISSUE THREAD

**Issue by mmiraglia** [edatfreecodecamp/python-math#1]
In math-code-test-b.py > step04, line 39, missing backslah:

 elif re.search("plt\.plot\(\[xmin\,xmax\]\,\[0\,0\]\,\s*\'b\'**\**)", code):

**Comment by edatfreecodecamp** [comment]
Thank you. I will fix that

Edward Pratowski
Math Teacher
***@***.***

**Comment by edatfreecodecamp** [comment]
I fixed that "unbalanced parentheses" error. Thanks again for telling me
about it

Edward Pratowski
Math Teacher
***@***.***

**Comment by edatfreecodecamp** [comment]
Fixed a while ago, just found the "close issue" button
